# Generated by Django 4.2 on 2023-08-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('credit', models.IntegerField(default=0, verbose_name='Merchant Credit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('phone', models.BigIntegerField(null=True, verbose_name='Phone Number')),
                ('amount', models.IntegerField(default=0, verbose_name='Charge Amount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b_charge.merchant', verbose_name='Merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
