# Generated by Django 4.2 on 2023-08-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_charge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='credit',
            field=models.PositiveIntegerField(default=0, verbose_name='Merchant Credit'),
        ),
    ]
